### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by maujim** [MatthewFilipovich/latex-plots#1]
hi I wanted to use this to make my matplotlib plots look less shitty but I don't know how to run the `README.md` file using python; please help

**Comment by MatthewFilipovich** [comment]
Hi @maujim, Unfortunately you need to know how to use LaTeX properly before using the repo. Please take a look at http://www.docs.is.ed.ac.uk/skills/documents/3722/3722-2014.pdf and http://www.sas.rochester.edu/psc/thestarlab/help/latextut0.pdf.
